site_name: Sinesp
theme:
  name: material
nav:
    - Home: index.md
    - Panejamento: Planning/planning.md
    - Pré-Rastreabilidade:
      - Rich picture: Pre-traceability/pre-traceability.md
    - Elicitação:
      - Brainstorming: Elicitation/brainstorming.md
      - Introspecção: Elicitation/introspection.md
      - Questionário: Elicitation/quiz.md
    - Priorização:
      - MoSCoW: Priorization/moscow.md
    - Modelagem:
      - Cenários: Modeling/scenarios.md
      - Léxicos: Modeling/lexicons.md
      - Use Case: Modeling/useCase.md
      - Especificação Suplementar: Modeling/supplementarySpecification.md
      - Backlog: Modeling/productBacklog.md
      - NFR Framework: Modeling/NFRFramework.md
    - Análise:
      - Verificação:
        - Rich Picture: Analysis/Verification/rich_picture.md
        - Cenários: Analysis/Verification/scenarios.md
        - Léxico : Analysis/Verification/Lexico.md
        - Use Case: Analysis/Verification/use_cases.md
        - Backlog: Analysis/Verification/backlog.md
        - NFR: Analysis/Verification/nfr.md
      - Validação: Analysis/validation.md
    - Equipe: Team/team.md
    - Entregas: ControlPoints/control_points.md
