site_name: Sinesp
theme:
  name: material
nav:
    - Home: index.md
    - Panejamento: Planning/planning.md
    # - Rastreabilidade:
    #   - Pré-Rastreabilidade:
    #   - Pós-Rastreabilidade:
    - Elicitação:
      - Brainstorming: Elicitation/brainstorming.md
      - Introspecção: Elicitation/introspection.md
    - Priorização:
      - MoSCoW: Priorization/moscow.md
    - Modelagem:
      - Cenários: Modeling/scenarios.md
      - Léxicos: Modeling/lexicons.md
      - Use Case: Modeling/useCase.md
      - Especificação Suplementar: Modeling/supplementarySpecification.md
    - Equipe: Team/team.md
    - Entregas: ControlPoints/control_points.md
